export const KNOWLEDGE_OBJECT_RELATION_GENERATION_STATUS = {
  PROCESSING: "PROCESSING",

  COMPLETED: "COMPLETED",

  FAILED: "FAILED",
} as const;

export type KnowledgeObjectRelationGenerationStatus =
  (typeof KNOWLEDGE_OBJECT_RELATION_GENERATION_STATUS)[keyof typeof KNOWLEDGE_OBJECT_RELATION_GENERATION_STATUS];
